language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
- pip install -r requirements.txt

before_script: flake8 gengo
# command to run tests
script: python setup.py test

notifications:
  irc: "irc.freenode.net#Gengo"
